### ISSUE TITLE
Problems with Kibana 'Request Dashboard' - can't find it

### ISSUE THREAD

**Issue by hank345** [stagemonitor/stagemonitor-mailinglist#26]
Hello,

I'm trying to setup a local installation of stagemonitor to monitor a REST API app running onJetty.
I see no problems in the logs. My app says "Measurement Session is initialized".
But I can't load the dashboard called "Request Dashboard" in Kibana (it says I have 0 dashboards).
I have tried a lot of different ElasticSearch & Kibana version combinations.

CURRENT SETUP:
**Java app (runs with Jetty):**
In my main class I do this just before starting Jetty: 
`Stagemonitor.init();`
I have a stagemonitor.properties looking like this:
```
stagemonitor.applicationName=Web App
stagemonitor.instanceName=localhost
stagemonitor.instrument.include=se.henrik
stagemonitor.elasticsearch.url=http://localhost:9200
```

**Elasticsearch**
Version: 2.1.2

**Kibana**
Version 4.3.3
(kibana.yml: elasticsearch.url: "http://localhost:9200")

When Kibana started I added an index pattern: stagemonitor-* (is that correct?)

Is there someone which can help me where to start looking?

**Comment by felixbarny** [comment]
Which stagemonitor dependencies do you currently have? You need `stagemonitor-web`. You don't need to manually add any index patterns as this should be done automatically. If you do have a dependency to `stagemonitor-web`, you could start debugging in `org.stagemonitor.requestmonitor.RequestMonitorPlugin#initializePlugin`. This is the place where the dashboards and index patterns should be populated.

**Comment by hank345** [comment]
Thanks Felix!
The dependency change fixed it, I had stagemonitor-core.. 
Now I can see the Dashboards :)
----Ursprungligt meddelande----
Från : notifications@github.com
Datum : 2016-04-20 - 11:36 (CEST)
Till : stagemonitor-mailinglist@noreply.github.com
Kopia : geijstedt@telia.com, author@noreply.github.com
Ämne : Re: [stagemonitor/stagemonitor-mailinglist] Problems with Kibana 'Request Dashboard' - can't find it (#26)
Which stagemonitor dependencies do you currently have? You need stagemonitor-web. You don't need to manually add any index patterns as this should be done automatically. If you do have a dependency to stagemonitor-web, you could start debugging in org.stagemonitor.requestmonitor.RequestMonitorPlugin#initializePlugin. This is the place where the dashboards and index patterns should be populated.

**Comment by felixbarny** [comment]
Great! Do you think there is any place in the docs where I could make this more clear?

**Comment by hank345** [comment]
Hmm.. not really. When I check the docs now it seems pretty clear.
I think my mistake was that I clicked the Maven central repo button which links to the core module:
http://search.maven.org/#artifactdetails%7Corg.stagemonitor%7Cstagemonitor-core%7C0.22.0%7C
..and I copied the Gradle link from there.
----Ursprungligt meddelande----
Från : notifications@github.com
Datum : 2016-04-20 - 13:05 (CEST)
Till : stagemonitor-mailinglist@noreply.github.com
Kopia : geijstedt@telia.com, author@noreply.github.com
Ämne : Re: [stagemonitor/stagemonitor-mailinglist] Problems with Kibana 'Request Dashboard' - can't find it (#26)
Great! Do you think there is any place in the docs where I could make this more clear?
