### ISSUE TITLE
JDBC Metrics for abstract classes

### ISSUE THREAD

**Issue by CptS** [stagemonitor/stagemonitor-mailinglist#33]
Hi,

I'm currently trying to understand the data captured by stagemonitor and my biggest problem is that it shows me many abstract class names.
For example we have a class `AbstractDAO` with a method `findOneById` and all our DAOs extend from this abstract DAO.
The kibana dashboard just shows me that `AbstractDAO#findOneById` is the _Most Frequent Query_ but this is not very helpful.
If I have a `class UsersDAO extends AbstractDAO` and someone calls the `findOneById` method on an instance of the `UsersDAO` it would be better to get `UsersDAO#findOneById` in the dashboard.

I hope you understand what I mean. Is there anything I can do?
Or are I'm completly on the wrong way?

**Comment by felixbarny** [comment]
Unfortunately, this behavior is in the nature of stack traces. So there is not a lot I can do about it. The only thing you could do is to create a custom timer in your AbstractDAO:

```java
public <T> T findOneById(Integer id, Class<T> clazz) {
	Metric2Registry registry = Stagemonitor.getMetric2Registry();
	final Timer.Context time = registry.timer(name("external_request_response_time").type("jdbc").tag("signature", getClass().getSimpleName() + "#findOneById").build()).time();
	try {
		return ...
	} finally {
		time.stop();
	}
}
```

Now you will also see for example `UsersDAO#findOneById` in the dashboard.
