### ISSUE TITLE
Automatic Request Grouping

### ISSUE THREAD

**Issue by hrzbrg** [stagemonitor/stagemonitor-mailinglist#48]
Hi (again),

we have been running Stagemonitor for the past weeks in a testing environment in several services now. We have some services with routes that include URL parameters like IDs, timestamps, location names etc. With a growing number of services it becomes very annoying to configure `stagemonitor.groupUrls`. 
It would be a great feature if Stagemonitor could learn whether a route contains dynamic urlparameters and group them automatically. That would be a great benefit. Maybe I can also get my team to have a look on how to accomplish that.

**Comment by felixbarny** [comment]
Are you using any mvc framework? Stagemonitor has support for Spring MVC and JAX-RS. It detects requests to controller methods and names the requests after those methods. Example: requests which are processed by `SearchController#doSearch` are by default named `Do Search`. You can also configure `SearchController#doSearch` and `SearchController.doSearch`.

So if you are using a similar framework, it would actually make sense to add support for that instead. It also reduces the overhead of regex parsing. See also [JaxRsRequestNameDeterminerTransformer](https://github.com/stagemonitor/stagemonitor/blob/0.80.0.RC1/stagemonitor-web-servlet/src/main/java/org/stagemonitor/web/servlet/jaxrs/JaxRsRequestNameDeterminerTransformer.java) and [SpringMvcRequestNameDeterminerTransformer](https://github.com/stagemonitor/stagemonitor/blob/0.80.0.RC1/stagemonitor-web-servlet/src/main/java/org/stagemonitor/web/servlet/spring/SpringMvcRequestNameDeterminerTransformer.java).

**Comment by hrzbrg** [comment]
Yes, we are mostly using SpringMVC. For some routes however we get the following results in Grafana:
![bildschirmfoto 2017-06-28 um 14 10 18](https://user-images.githubusercontent.com/199414/27637508-4636b6ea-5c10-11e7-981a-6935510928e6.png)

**Comment by felixbarny** [comment]
Is the route `/driver/v1/booking/{id}` also handled by Spring MVC? Is there anything special in the controller method? Did you manually map `Update Booking` or did stagemonitor automatically detect that?

P.S: nice response times ;)

**Comment by hrzbrg** [comment]
Puh well, we found the intruder. Thats awkward. Request Mapping for Sprint MVC requests works fine, but there was a misconfigured container in another environment that reported it like that. Mea culpa.
